### ISSUE TITLE
Issue with upgrading to kernel 5.4.0-42-generic

### ISSUE THREAD

**Issue by dimucciojonathan** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#6]
I've been looking around (since this isn't an issue with the guide) but couldn't find an answer to my question.

When installing Ubuntu 20.04.3 fresh, I start with kernel `5.11.0-34-generic`. Then after following through the steps, I have no other available kernels in the grub boot menu. I'm fairly new to Ubuntu/Linux, so I have no idea what else to do.

I have a RX 580 of course, i5 9400F, gigabyte z390 SLI.

**Comment by Grench6** [comment]
Hi @dimucciojonathan.

First you should check if the kernel *is* installed:
`dpkg --list | grep linux-image`

If there are no other kernels (other than `5.11.0-34-generic`), then you should install it first:
`apt install linux-image-5.4.0-42-generic`

Reboot, go to grub, and try again. If it is still not working, then something else is happening. You could try something like [this](https://serverascode.com/2019/05/17/install-and-boot-older-kernel-ubuntu.html).

**Comment by Grench6** [comment]
Ubuntu has a weird kernel release/support model which they call **Rolling LTS Enablement Stack**, otherwise known as **HWE** (Hardware Enablement). You can read more about it [here](https://wiki.ubuntu.com/Kernel/LTSEnablementStack).

By default, it is enabled, so when you downloaded Ubuntu Desktop 20.04 it comes **only with the newest** supported kernel. This is not what we want, but there are a couple of ways to get our desired kernel. The simplest one is to install the GA kernel (5.4 in the case of Ubuntu 20.04):
`sudo apt install --install-recommends linux-generic`

Once you reboot and go to GRUB, you will see your newly installed kernel available.

**Comment by Grench6** [comment]
I've also updated the guide to make this more clear, let me know if it works.
